from __future__ import annotations

import pytest

from geass.config import load_config, user_env_path


@pytest.fixture(autouse=True)
def isolated_home(monkeypatch, tmp_path):
    """隔离真实用户目录，避免读取 ~/.geass/env.toml 影响断言。"""
    monkeypatch.setenv("GEASS_HOME", str(tmp_path / "home"))


def test_load_config_file(tmp_path):
    path = tmp_path / "config.toml"
    path.write_text(
        '[server]\nport = 9000\ntoken = "abc"\n[agent]\nmodel = "gpt-x"\n',
        encoding="utf-8",
    )
    config = load_config(path)
    assert config.server.port == 9000
    assert config.server.token == "abc"
    assert config.agent.model == "gpt-x"


def test_env_overrides(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text('[server]\ntoken = "file-token"\n', encoding="utf-8")
    monkeypatch.setenv("GEASS_TOKEN", "env-token")
    monkeypatch.setenv("GEASS_API_KEY", "sk-test")
    config = load_config(path)
    assert config.server.token == "env-token"
    assert config.api_key == "sk-test"


def test_token_autogenerated(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text("", encoding="utf-8")
    monkeypatch.delenv("GEASS_TOKEN", raising=False)
    config = load_config(path)
    assert config.server.token


def test_base_url_and_model_from_file(tmp_path):
    path = tmp_path / "config.toml"
    path.write_text(
        '[agent]\nbase_url = "https://api.deepseek.com"\nmodel = "deepseek-chat"\n',
        encoding="utf-8",
    )
    config = load_config(path)
    assert config.agent.base_url == "https://api.deepseek.com"
    assert config.agent.model == "deepseek-chat"


def test_env_overrides_base_url_and_key(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text(
        '[agent]\nbase_url = "https://api.openai.com/v1"\n', encoding="utf-8"
    )
    monkeypatch.setenv("GEASS_BASE_URL", "https://api.deepseek.com")
    monkeypatch.setenv("GEASS_API_KEY", "sk-deepseek")
    monkeypatch.setenv("GEASS_MODEL", "deepseek-v4-flash")
    config = load_config(path)
    assert config.agent.base_url == "https://api.deepseek.com"
    assert config.agent.model == "deepseek-v4-flash"
    assert config.api_key == "sk-deepseek"


def test_user_env_merged(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text('[agent]\nmodel = "gpt-x"\n', encoding="utf-8")
    home = tmp_path / "home"
    monkeypatch.setenv("GEASS_HOME", str(home))
    user_env = home / ".geass" / "env.toml"
    user_env.parent.mkdir(parents=True)
    user_env.write_text(
        '[agent]\nmodel = "deepseek-chat"\nbase_url = "https://api.deepseek.com"\n'
        'api_key = "sk-user"\n',
        encoding="utf-8",
    )
    config = load_config(project)
    assert config.agent.model == "deepseek-chat"
    assert config.agent.base_url == "https://api.deepseek.com"
    assert config.api_key == "sk-user"


def test_env_beats_user_env(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    home = tmp_path / "home"
    monkeypatch.setenv("GEASS_HOME", str(home))
    user_env = home / ".geass" / "env.toml"
    user_env.parent.mkdir(parents=True)
    user_env.write_text(
        '[agent]\nmodel = "deepseek-chat"\n', encoding="utf-8"
    )
    monkeypatch.setenv("GEASS_MODEL", "deepseek-reasoner")
    config = load_config(project)
    assert config.agent.model == "deepseek-reasoner"


def test_persist_writes_user_env(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    home = tmp_path / "home"
    monkeypatch.setenv("GEASS_HOME", str(home))
    monkeypatch.setenv("GEASS_API_KEY", "sk-persist")
    monkeypatch.setenv("GEASS_BASE_URL", "https://api.deepseek.com")
    monkeypatch.setenv("GEASS_MODEL", "deepseek-v4-flash")

    first = load_config(project, persist=True)
    assert user_env_path().exists()

    # 清除环境变量后重载，值应从 env.toml 恢复
    for key in (
        "GEASS_API_KEY",
        "GEASS_BASE_URL",
        "GEASS_MODEL",
    ):
        monkeypatch.delenv(key)
    second = load_config(project)
    assert first.api_key == second.api_key == "sk-persist"
    assert second.agent.base_url == "https://api.deepseek.com"
    assert second.agent.model == "deepseek-v4-flash"


def test_token_random_each_load(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    monkeypatch.setenv("GEASS_HOME", str(tmp_path / "home"))
    monkeypatch.delenv("GEASS_TOKEN", raising=False)

    first = load_config(project)
    second = load_config(project)
    assert first.server.token
    assert first.server.token != second.server.token


def test_token_env_override(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    monkeypatch.setenv("GEASS_TOKEN", "fixed-via-env")
    config = load_config(project)
    assert config.server.token == "fixed-via-env"
