from __future__ import annotations

from geass.config import load_config


def test_load_config_file(tmp_path):
    path = tmp_path / "config.toml"
    path.write_text(
        '[server]\nport = 9000\ntoken = "abc"\n[agent]\nmodel = "gpt-x"\n',
        encoding="utf-8",
    )
    config = load_config(path)
    assert config.server.port == 9000
    assert config.server.token == "abc"
    assert config.agent.model == "gpt-x"


def test_env_overrides(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text('[server]\ntoken = "file-token"\n', encoding="utf-8")
    monkeypatch.setenv("GEASS_TOKEN", "env-token")
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
    config = load_config(path)
    assert config.server.token == "env-token"
    assert config.openai_api_key == "sk-test"


def test_token_autogenerated(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text("", encoding="utf-8")
    monkeypatch.delenv("GEASS_TOKEN", raising=False)
    config = load_config(path)
    assert config.server.token


def test_base_url_from_file(tmp_path):
    path = tmp_path / "config.toml"
    path.write_text(
        '[agent]\nbase_url = "https://api.deepseek.com"\nmodel = "deepseek-chat"\n',
        encoding="utf-8",
    )
    config = load_config(path)
    assert config.agent.base_url == "https://api.deepseek.com"
    assert config.agent.model == "deepseek-chat"


def test_env_overrides_base_url_and_key(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text('[agent]\nbase_url = "https://api.openai.com/v1"\n', encoding="utf-8")
    monkeypatch.setenv("GEASS_BASE_URL", "https://api.deepseek.com")
    monkeypatch.setenv("DEEPSEEK_API_KEY", "sk-deepseek")
    config = load_config(path)
    assert config.agent.base_url == "https://api.deepseek.com"
    assert config.openai_api_key == "sk-deepseek"


def test_geass_api_key_has_priority(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text("", encoding="utf-8")
    monkeypatch.setenv("OPENAI_API_KEY", "sk-openai")
    monkeypatch.setenv("DEEPSEEK_API_KEY", "sk-deepseek")
    monkeypatch.setenv("GEASS_API_KEY", "sk-geass")
    config = load_config(path)
    assert config.openai_api_key == "sk-geass"
