from __future__ import annotations

import pytest

from geass.config import load_config, user_env_path


@pytest.fixture(autouse=True)
def isolated_home(monkeypatch, tmp_path):
    """隔离真实用户目录，避免读取 ~/.geass/env.toml 影响断言。"""
    monkeypatch.setenv("GEASS_HOME", str(tmp_path / "home"))


def test_load_config_file(tmp_path):
    path = tmp_path / "config.toml"
    path.write_text(
        '[server]\nport = 9000\ntoken = "abc"\n[agent]\nmodel = "gpt-x"\n',
        encoding="utf-8",
    )
    config = load_config(path)
    assert config.server.port == 9000
    assert config.server.token == "abc"
    assert config.agent.model == "gpt-x"


def test_env_overrides(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text('[server]\ntoken = "file-token"\n', encoding="utf-8")
    monkeypatch.setenv("GEASS_TOKEN", "env-token")
    monkeypatch.setenv("GEASS_API_KEY", "sk-test")
    config = load_config(path)
    assert config.server.token == "env-token"
    assert config.api_key == "sk-test"


def test_token_autogenerated(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text("", encoding="utf-8")
    monkeypatch.delenv("GEASS_TOKEN", raising=False)
    config = load_config(path)
    assert config.server.token


def test_base_url_and_model_from_file(tmp_path):
    path = tmp_path / "config.toml"
    path.write_text(
        '[agent]\nbase_url = "https://api.deepseek.com"\nmodel = "deepseek-chat"\n',
        encoding="utf-8",
    )
    config = load_config(path)
    assert config.agent.base_url == "https://api.deepseek.com"
    assert config.agent.model == "deepseek-chat"


def test_env_overrides_base_url_and_key(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text(
        '[agent]\nbase_url = "https://api.openai.com/v1"\n', encoding="utf-8"
    )
    monkeypatch.setenv("GEASS_BASE_URL", "https://api.deepseek.com")
    monkeypatch.setenv("GEASS_API_KEY", "sk-deepseek")
    monkeypatch.setenv("GEASS_MODEL", "deepseek-v4-flash")
    config = load_config(path)
    assert config.agent.base_url == "https://api.deepseek.com"
    assert config.agent.model == "deepseek-v4-flash"
    assert config.api_key == "sk-deepseek"


def test_user_env_merged(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text('[agent]\nmodel = "gpt-x"\n', encoding="utf-8")
    home = tmp_path / "home"
    monkeypatch.setenv("GEASS_HOME", str(home))
    user_env = home / ".geass" / "env.toml"
    user_env.parent.mkdir(parents=True)
    user_env.write_text(
        '[agent]\nmodel = "deepseek-chat"\nbase_url = "https://api.deepseek.com"\n'
        'api_key = "sk-user"\n',
        encoding="utf-8",
    )
    config = load_config(project)
    assert config.agent.model == "deepseek-chat"
    assert config.agent.base_url == "https://api.deepseek.com"
    assert config.api_key == "sk-user"


def test_env_beats_user_env(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    home = tmp_path / "home"
    monkeypatch.setenv("GEASS_HOME", str(home))
    user_env = home / ".geass" / "env.toml"
    user_env.parent.mkdir(parents=True)
    user_env.write_text(
        '[agent]\nmodel = "deepseek-chat"\n', encoding="utf-8"
    )
    monkeypatch.setenv("GEASS_MODEL", "deepseek-reasoner")
    config = load_config(project)
    assert config.agent.model == "deepseek-reasoner"


def test_persist_writes_user_env(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    home = tmp_path / "home"
    monkeypatch.setenv("GEASS_HOME", str(home))
    monkeypatch.setenv("GEASS_API_KEY", "sk-persist")
    monkeypatch.setenv("GEASS_BASE_URL", "https://api.deepseek.com")
    monkeypatch.setenv("GEASS_MODEL", "deepseek-v4-flash")

    first = load_config(project, persist=True)
    assert user_env_path().exists()

    # 清除环境变量后重载，值应从 env.toml 恢复
    for key in (
        "GEASS_API_KEY",
        "GEASS_BASE_URL",
        "GEASS_MODEL",
    ):
        monkeypatch.delenv(key)
    second = load_config(project)
    assert first.api_key == second.api_key == "sk-persist"
    assert second.agent.base_url == "https://api.deepseek.com"
    assert second.agent.model == "deepseek-v4-flash"


def test_token_random_each_load(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    monkeypatch.setenv("GEASS_HOME", str(tmp_path / "home"))
    monkeypatch.delenv("GEASS_TOKEN", raising=False)

    first = load_config(project)
    second = load_config(project)
    assert first.server.token
    assert first.server.token != second.server.token


def test_token_env_override(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    monkeypatch.setenv("GEASS_TOKEN", "fixed-via-env")
    config = load_config(project)
    assert config.server.token == "fixed-via-env"


def test_ocr_defaults(tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")

    config = load_config(project)

    assert config.agent.ocr is True
    assert config.agent.ocr_token == ""
    assert config.agent.ocr_model == "PaddleOCR-VL-1.6"
    assert config.agent.ocr_base_url == "https://paddleocr.aistudio-app.com"
    assert config.agent.ocr_timeout == 90.0


def test_ocr_env_overrides(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text(
        '[agent]\nocr_model = "PP-StructureV3"\n'
        'ocr_base_url = "https://old.test"\n',
        encoding="utf-8",
    )
    monkeypatch.setenv("GEASS_PADDLEOCR_TOKEN", "env-ocr-token")
    monkeypatch.setenv("GEASS_PADDLEOCR_MODEL", "PaddleOCR-VL-1.6")
    monkeypatch.setenv("GEASS_PADDLEOCR_BASE_URL", "https://new.test")

    config = load_config(project)

    assert config.agent.ocr_token == "env-ocr-token"
    assert config.agent.ocr_model == "PaddleOCR-VL-1.6"
    assert config.agent.ocr_base_url == "https://new.test"


def test_ocr_token_mcp_env_fallback(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    monkeypatch.setenv("PADDLEOCR_MCP_AISTUDIO_ACCESS_TOKEN", "mcp-token")

    config = load_config(project)

    assert config.agent.ocr_token == "mcp-token"


def test_ocr_settings_from_user_env(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    home = tmp_path / "home"
    monkeypatch.setenv("GEASS_HOME", str(home))
    user_env = home / ".geass" / "env.toml"
    user_env.parent.mkdir(parents=True)
    user_env.write_text(
        '[agent]\nocr_token = "user-ocr"\nocr_model = "PP-StructureV3"\n',
        encoding="utf-8",
    )

    config = load_config(project)

    assert config.agent.ocr_token == "user-ocr"
    assert config.agent.ocr_model == "PP-StructureV3"


def test_ocr_persist_writes_user_env(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    home = tmp_path / "home"
    monkeypatch.setenv("GEASS_HOME", str(home))
    monkeypatch.setenv("GEASS_PADDLEOCR_TOKEN", "persist-ocr")
    monkeypatch.setenv("GEASS_PADDLEOCR_MODEL", "PP-StructureV3")
    monkeypatch.setenv("GEASS_PADDLEOCR_BASE_URL", "https://persist.test")

    load_config(project, persist=True)
    assert user_env_path().exists()

    for key in (
        "GEASS_PADDLEOCR_TOKEN",
        "GEASS_PADDLEOCR_MODEL",
        "GEASS_PADDLEOCR_BASE_URL",
    ):
        monkeypatch.delenv(key)
    config = load_config(project)
    assert config.agent.ocr_token == "persist-ocr"
    assert config.agent.ocr_model == "PP-StructureV3"
    assert config.agent.ocr_base_url == "https://persist.test"


def test_ocr_token_masked_in_show(monkeypatch, tmp_path):
    project = tmp_path / "config.toml"
    project.write_text("", encoding="utf-8")
    monkeypatch.setenv("GEASS_HOME", str(tmp_path / "home"))
    monkeypatch.setenv("GEASS_PADDLEOCR_TOKEN", "secret-ocr-token-value")

    from geass.config import mask_secret

    config = load_config(project)
    assert mask_secret(config.agent.ocr_token) == "secr...alue"
